package hibernate.pojo;
// Generated 3 Jun, 2015 5:12:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblCard generated by hbm2java
 */
public class TblCard  implements java.io.Serializable {


     private String CCardId;
     private TblPlant tblPlant;
     private Set<TblVehicleFlight> tblVehicleFlights = new HashSet<TblVehicleFlight>(0);
     private Set<TblMapping> tblMappings = new HashSet<TblMapping>(0);

    public TblCard() {
    }

	
    public TblCard(String CCardId, TblPlant tblPlant) {
        this.CCardId = CCardId;
        this.tblPlant = tblPlant;
    }
    public TblCard(String CCardId, TblPlant tblPlant, Set<TblVehicleFlight> tblVehicleFlights, Set<TblMapping> tblMappings) {
       this.CCardId = CCardId;
       this.tblPlant = tblPlant;
       this.tblVehicleFlights = tblVehicleFlights;
       this.tblMappings = tblMappings;
    }
   
    public String getCCardId() {
        return this.CCardId;
    }
    
    public void setCCardId(String CCardId) {
        this.CCardId = CCardId;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public Set<TblVehicleFlight> getTblVehicleFlights() {
        return this.tblVehicleFlights;
    }
    
    public void setTblVehicleFlights(Set<TblVehicleFlight> tblVehicleFlights) {
        this.tblVehicleFlights = tblVehicleFlights;
    }
    public Set<TblMapping> getTblMappings() {
        return this.tblMappings;
    }
    
    public void setTblMappings(Set<TblMapping> tblMappings) {
        this.tblMappings = tblMappings;
    }




}


