package hibernate.pojo;
// Generated Jun 21, 2015 11:42:38 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TblPaths generated by hbm2java
 */
public class TblPaths  implements java.io.Serializable {


     private BigDecimal IPathId;
     private TblPlant tblPlant;
     private String TName;
     private String TArrPath;

    public TblPaths() {
    }

    public TblPaths(BigDecimal IPathId, TblPlant tblPlant, String TName, String TArrPath) {
       this.IPathId = IPathId;
       this.tblPlant = tblPlant;
       this.TName = TName;
       this.TArrPath = TArrPath;
    }
   
    public BigDecimal getIPathId() {
        return this.IPathId;
    }
    
    public void setIPathId(BigDecimal IPathId) {
        this.IPathId = IPathId;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public String getTName() {
        return this.TName;
    }
    
    public void setTName(String TName) {
        this.TName = TName;
    }
    public String getTArrPath() {
        return this.TArrPath;
    }
    
    public void setTArrPath(String TArrPath) {
        this.TArrPath = TArrPath;
    }




}


