package hibernate.pojo;
// Generated 3 Jun, 2015 5:12:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblVehicle generated by hbm2java
 */
public class TblVehicle  implements java.io.Serializable {


     private String TVehicleId;
     private TblPlant tblPlant;
     private TblTransporter tblTransporter;
     private String TChasisNo;
     private String TVehicleType;
     private Long ILoadCapacity;
     private String TNationalPermit;
     private Date dtLicenseExpiryDate;
     private String TOwner;
     private Set<TblMapping> tblMappings = new HashSet<TblMapping>(0);

    public TblVehicle() {
    }

	
    public TblVehicle(String TVehicleId, TblPlant tblPlant, TblTransporter tblTransporter) {
        this.TVehicleId = TVehicleId;
        this.tblPlant = tblPlant;
        this.tblTransporter = tblTransporter;
    }
    public TblVehicle(String TVehicleId, TblPlant tblPlant, TblTransporter tblTransporter, String TChasisNo, String TVehicleType, Long ILoadCapacity, String TNationalPermit, Date dtLicenseExpiryDate, String TOwner, Set<TblMapping> tblMappings) {
       this.TVehicleId = TVehicleId;
       this.tblPlant = tblPlant;
       this.tblTransporter = tblTransporter;
       this.TChasisNo = TChasisNo;
       this.TVehicleType = TVehicleType;
       this.ILoadCapacity = ILoadCapacity;
       this.TNationalPermit = TNationalPermit;
       this.dtLicenseExpiryDate = dtLicenseExpiryDate;
       this.TOwner = TOwner;
       this.tblMappings = tblMappings;
    }
   
    public String getTVehicleId() {
        return this.TVehicleId;
    }
    
    public void setTVehicleId(String TVehicleId) {
        this.TVehicleId = TVehicleId;
    }
    public TblPlant getTblPlant() {
        return this.tblPlant;
    }
    
    public void setTblPlant(TblPlant tblPlant) {
        this.tblPlant = tblPlant;
    }
    public TblTransporter getTblTransporter() {
        return this.tblTransporter;
    }
    
    public void setTblTransporter(TblTransporter tblTransporter) {
        this.tblTransporter = tblTransporter;
    }
    public String getTChasisNo() {
        return this.TChasisNo;
    }
    
    public void setTChasisNo(String TChasisNo) {
        this.TChasisNo = TChasisNo;
    }
    public String getTVehicleType() {
        return this.TVehicleType;
    }
    
    public void setTVehicleType(String TVehicleType) {
        this.TVehicleType = TVehicleType;
    }
    public Long getILoadCapacity() {
        return this.ILoadCapacity;
    }
    
    public void setILoadCapacity(Long ILoadCapacity) {
        this.ILoadCapacity = ILoadCapacity;
    }
    public String getTNationalPermit() {
        return this.TNationalPermit;
    }
    
    public void setTNationalPermit(String TNationalPermit) {
        this.TNationalPermit = TNationalPermit;
    }
    public Date getDtLicenseExpiryDate() {
        return this.dtLicenseExpiryDate;
    }
    
    public void setDtLicenseExpiryDate(Date dtLicenseExpiryDate) {
        this.dtLicenseExpiryDate = dtLicenseExpiryDate;
    }
    public String getTOwner() {
        return this.TOwner;
    }
    
    public void setTOwner(String TOwner) {
        this.TOwner = TOwner;
    }
    public Set<TblMapping> getTblMappings() {
        return this.tblMappings;
    }
    
    public void setTblMappings(Set<TblMapping> tblMappings) {
        this.tblMappings = tblMappings;
    }




}


